import { execSync } from "node:child_process";

// Seeds the demo SQLite DB (idempotent) so the E2E web server has the seeded
// accounts + demo profile. Set E2E_SKIP_SEED=1 to skip on fast local reruns.
export default async function globalSetup() {
  if (process.env.E2E_SKIP_SEED === "1") {
    console.log("[e2e] E2E_SKIP_SEED=1 — skipping demo seed");
    return;
  }
  // Uses setup:e2e (db push + seeds) rather than setup:demo — it skips
  // `prisma generate` so it never races the engine .dll lock on Windows. The
  // client is already generated by `postinstall` on a clean checkout / in CI.
  console.log("[e2e] seeding demo DB (npm run setup:e2e)…");
  execSync("npm run setup:e2e", { stdio: "inherit" });
}
